add_friends/urls.py
from django.conf.urls import url
from .views import index,add

urlpatterns = [
	url(r'^$', index, name='index'),
	url(r'^add',add, name='add'),
]

halaman_profile/urls.py
from django.conf.urls import url
from .views import index
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
]

menu_stats/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
    url(r'^$', index, name='index'),
    
]

tugasSatu/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import update_status.urls as update_status
import add_friends.urls as add_friends
from django.views.generic.base import RedirectView
import halaman_profile.urls as halaman_profile
import menu_stats.urls as menu_stats

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^update-status/', include(update_status,namespace='update-status')),
    url(r'^add-friends/',include(add_friends,namespace='add-friends')),
    url(r'^$', RedirectView.as_view(url='/update-status/', permanent = True), name = 'index'),
    url(r'^halaman-profile/', include(halaman_profile, namespace ='halaman-profile')),
    url(r'^menu-stats/', include(menu_stats, namespace ='menu-stats')),
]

update_status/urls.py
from django.conf.urls import url
from .views import index, add_todo, delete_status
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_todo', add_todo, name='add_todo'),
    url(r'^delete_status/(?P<id_status>\d+)/$', delete_status, name = 'delete_status'),
]

add_friends/models.py
from django.db import models

# Create your models here.
class Add(models.Model):
	name = models.CharField(max_length=30)
	url = models.URLField(max_length=100)
	created_date = models.DateTimeField(auto_now_add=True)

halaman_profile/models.py
from django.db import models

# Create your models here.
class Profiledata(models.Model):
	name = models.CharField(max_length=250)
	Birthday = models.CharField(max_length=20)
	Gender = models.CharField(max_length=200)
	expertise = models.TextField(max_length=200)
	Description = models.CharField(max_length=200)
	Email = models.CharField(max_length=200)

menu_stats/models.py
from django.db import models

# Create your models here.

update_status/models.py
from django.db import models

class Todo(models.Model):
	description = models.TextField()
	created_date = models.DateTimeField(auto_now_add=True)

add_friends/forms.py
from django import forms

class AddFriends_Form(forms.Form):
	error_messages = {
		'required' : "Harap mengisi input ini",
	}
	name_attributes = {
	'type' : 'text',
	'class' : 'input_name',
	'placeholder' : "Input your friend's name here...",
	}
	url_attributes = {
	'type' : 'text',
	'class' : 'input_url',
	'rows' : 2,
	'cols' : 50,
	'placeholder' : "Input your friend's URL here...",
	}

	name = forms.CharField(label='Name',required=True,max_length=30,widget=forms.TextInput(attrs=name_attributes))

	url = forms.URLField(label='URL',required=True,widget=forms.TextInput(attrs=url_attributes))

menu_stats/forms.py
from django import forms

class Todo_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
    }
    title_attrs = {
        'type': 'text',
        'class': 'todo-form-input',        
        'placeholder':'Masukan judul...'
    }
    description_attrs = {
        'type': 'text',
        'cols': 50,
        'rows': 4,
        'class': 'todo-form-textarea',
        'placeholder':'Masukan deskripsi...'
    }

    title = forms.CharField(label='', required=True, max_length=27, widget=forms.TextInput(attrs=title_attrs))
    description = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=description_attrs))

update_status/forms.py
from django import forms

class Form_status(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
    }
    description_attrs = {
        'type': 'text',
        'cols': 100,
        'rows': 4,
        'class': 'todo-form-textarea',
        'placeholder':'Apa yang anda pikirkan?'
    }

    description = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=description_attrs))

add_friends/views.py
from django.shortcuts import render
from .models import Add
from .forms import AddFriends_Form
from django.http import HttpResponseRedirect

# Create your views here.
response = {}
def index(request): #cuma nampillin halaman add-friends
	response['author'] = "Rani Lasma Uli"
	response['friends'] = Add.objects.order_by('-id')
	response['add_friends_form'] = AddFriends_Form
	html = 'add_friends/add_friends.html'
	return render(request,html,response)

def add(request):
    form = AddFriends_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['name'] = request.POST['name']
        response['url'] = request.POST['url']
        add = Add(name=response['name'],url=response['url'])
        add.save()
        return HttpResponseRedirect('/add-friends/')
    else:
        return HttpResponseRedirect('/add-friends/')

halaman_profile/views.py
from django.shortcuts import render
from datetime import datetime, date
from .models import Profiledata

# Create your views here.
profile_name = 'Gigi Hadid' #TODO implement your name here
birth_date = date(1995,4,23) #TODO implement your birthday
birthdate = birth_date.strftime('%d %B %Y')
gender = 'Female' #TODO implement your gender
email = 'gigihadid@gmail.com' #TODO implement your email
desc_profile = "victoria's secret model lalala lilili yeyeye"
#TODO implement your expertise minimal 3
expert = ["fashion model", "actress", "wawww"]

profil = Profiledata(name = profile_name, Birthday = birthdate, Gender= gender, Email = email, Description=desc_profile, expertise=expert)

def index(request):
	#response['author'] = "Redhita Putri"
	#response['Name'] = Profile.Name
	#response['Birthday'] = Profile.Birthday
	#response['Gender'] = Profile.Gender
	#response['expertise'] = Profile.expertise
	#response['Email'] = Profile.Email
	#response['Description'] = Profile.Description
	response = {'name' : profil.name, 'Birthday' : profil.Birthday, 'Gender': profil.Gender, 'expertise': profil.expertise, 'Description' : profil.Description, 'Email': profil.Email}
	html = 'halaman_profile/halaman_profile.html'
	return render(request, html, response)	

menu_stats/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from add_friends.models import Add
from update_status.models import Todo
from halaman_profile.views import profile_name

# Create your views here.
response = {}
def index(request):    
    response['author'] = "Rebecca" #TODO Implement yourname
    
    bnyk_temen = Add.objects.all().count()
    response['temen']= bnyk_temen 

    bnyk_status = Todo.objects.all().count()
    response['status'] = bnyk_status

    nama_profile = profile_name
    response['namaP'] = nama_profile

    if bnyk_status > 0:
        response['lastT'] = Todo.objects.last().created_date
        response['lastP'] = Todo.objects.last().description
    else:
        response['lastT'] = "__-__"
        response['lastP'] = "no post"

    html = 'menu_stats/menu_stats.html'
    
    return render(request, html, response)

update_status/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Form_status
from .models import Todo
from halaman_profile.views import profil
# Create your views here.
response = {}
def index(request):
	response['author'] = "Cut Syifa Salvira" #TODO Implement yourname
	response['profile_name'] = profil.name
	todo = Todo.objects.order_by('-id')
	response['todo'] = todo
	html = 'update_status/update_status.html'
	response['todo_form'] = Form_status
	return render(request, html, response)

def add_todo(request):
	form = Form_status(request.POST or None)
	if(request.method == 'POST' and form.is_valid()):
		response['description'] = request.POST['description']
		todo = Todo(description=response['description'])
		todo.save()
		return HttpResponseRedirect('/update-status/')
	else:
		return HttpResponseRedirect('/update-status/')

def delete_status(request, id_status):
    status = Todo.objects.get(pk = id_status)
    status.delete()
    return HttpResponseRedirect('/update-status/')

add_friends/templates/add_friends/add_friends.html
{% extends "layout/base.html" %}


{% block content %}
<style type="text/css">
	section{
  min-height: 400px;
}
</style>
<h1 class="main-title-add">ADD FRIENDS</h1>
<link href="//netdna.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
<hr/>
<section name="input-list" id="input-list">
    <div class="container">
    	<form id="form" method="POST" action="{% url 'add-friends:add' %}">
    		{% csrf_token %}
    		{{ add_friends_form }}
    		<input id="submit" type="submit" class="btn btn-lg btn-block btn-info" value="Submit">
    		<br>
    	</form>
    </div>
</section>

<section name="my-friends" id="my-friends" style="padding-bottom: 100px">
	<div class="container">
		<h2 class="my-list-title">My Friends</h2>
		<div class="flex">
			{% if friends %}
				{% for data in friends %}
					<div class="friends-item">
						<div class="friends-item-name" style="background-color: grey">
							{{data.name}}
						</div>
                        <div class="frieds-item-date">
                            {{data.created_date}}
                        </div>
						<div class="friends-item-url"">
							{{data.url}}
						</div>
					</div>
					<div class="distance">
						<br>
					</div>
				{% endfor %}
            {% else %}
            <div class="alert alert-dark text-center">
                <strong>Oops!</strong> You haven't have any friends yet:(.
            </div>
            {% endif %}

		</div>
	</div>
</section>
{% endblock %}        

halaman_profile/templates/halaman_profile/halaman_profile.html
{% extends "layout/base.html" %}

{% block content %}
	<div class="container text-center" id="profile-page" style="margin-top: 125px;">
		<div class = "left_top">
			<h4 style="text-align:left;">Profile</h4>
		</div>
			<img class = "img-circle" src ="https://assets.teenvogue.com/photos/59922529fc885e5cc9aba96e/master/pass/GettyImages-546939180.jpg" alt = "Gigi Hadid">
			
			<h3 align = "center" ><strong><strong>{{ name }}</strong></strong></h3>

				<table align = "center" style="text-align: center">
				<tr>
					<td align = "left"><h4>Birthday</h4></td>
					<td align = "left"><h4>{{ Birthday }}</h4></td>
				</tr>
				<tr>
					<td align = "left"><h4>Gender</h4></td>
					<td align = "left"><h4>{{ Gender }}</h4></td>
				</tr>
				<tr>
					<td align = "left"><h4>Expertise</h4></td>
					<td align = "left">
						<h4>
						<ul>
							{% for ii in expertise %}
								<li class="li1">{{ ii }}</li>
							{% endfor %}
							</h4>
						</ul>
					</td>
					
				</tr>
				<tr>
					<td align = "left"><h4>Description</h4></td>
					<td align = "left"><h4>{{  Description }}</h></td>
				</tr>
				<tr>
					<td align = "left"><h4>Email</h4></td>
					<td align = "left"><h4>{{ Email }}</h4></td>
				</tr> 
				</table>
			</div>
}
	

{% endblock %}

menu_stats/templates/menu_stats/menu_stats.html
{% extends "layout/base.html" %} 
{% block content %}
<div class="container"  style="margin-top: 60px;">
    <div class="row">
            <div class="col-sm-8 col-sm-offset-2">
                <h2 class="text-left"> Statistics </h2>
                <div class="media">
                    <div class="media-left media-middle">
                        <img src="https://assets.teenvogue.com/photos/59922529fc885e5cc9aba96e/master/pass/GettyImages-546939180.jpg" class="media-object img-circle" style="width: 205px">
                    </div>
                    <div class="media-body">
                        <h1 style="padding-top: 50px; padding-left: 20px"><strong>{{namaP}}</strong></h1>
                    </div>
                </div>
            </div>
        </div>

</div>

<div class="container"  style="margin-top: 60px;">
	<div class="row text-center">
		<div class="col-sm-8 col-sm-offset-2">
			<div class="col-sm-6">
				<h3><strong>Friends:</strong> {{temen}} People</h3>
			</div>
			<div class="col-sm-6">
				<h3><strong>Feeds:</strong> {{status}} Post</h3>
			</div>
		</div>
	</div>
</div>
<div class="container"  style="margin-top: 60px;">
	<div class="row">
		<div class="col-sm-8 col-sm-offset-2 bg1">
			<strong><h1>Latest Post:</h1></strong>
            <div class="media">
                <div class="media-left">
                    <img src="https://assets.teenvogue.com/photos/59922529fc885e5cc9aba96e/master/pass/GettyImages-546939180.jpg" class="media-object img-thumbnail" style="width:60px">
                </div>
            <div class="media-body">
                <h4 class="media-heading" style="margin-top: 20px"><strong>{{namaP}}</strong></h4>
            </div>
            {% if lastP %}
            <p>{{lastP}}</p>
            <p><small>Posted on {{lastT}}</small></p>
            </div>
            
            
{% endif %}
            
            

		</div>
	</div>
</div>


{% endblock %}

update_status/templates/layout/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="UPDATE STATUS">
    <meta name="author" content="{{author}}">
    <!-- bootstrap csss -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Ubuntu" rel="stylesheet"> 
    <link rel="stylesheet" type="text/css" href="{% static 'css/my_css2.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'add_friends2.css' %}" />
    <link href='https://fonts.googleapis.com/css?family=Raleway' rel='stylesheet' type='text/css'>

    <title>
        {% block title %} Ling In by Kelompok 9 {% endblock %}
    </title>
</head>

<body>
    <header>
        {% include "partial/header.html" %}
    </header>
    <content >
            {% block content %}
                <!-- content goes here -->
            {% endblock %}
    </content>
    <div class="footer" >
        <!-- TODO Block Footer dan include footer.html -->
        
        {% include "partial/footer.html" %}
        
    </div>

    
</body>
<!-- Jquery n Bootstrap Script -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script type="application/javascript">
      $(function() {
          $('a[href*="#"]:not([href="#"])').click(function() {
            if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'') && location.hostname == this.hostname) {
              var target = $(this.hash);
              target = target.length ? target : $('[name=' + this.hash.slice(1) +']');
              if (target.length) {
                $('html, body').animate({
                  scrollTop: target.offset().top - 55
                }, 1000);
                return false;
              }
            }
          });
        });
    </script>
</html>

update_status/templates/partial/footer.html
Copyright 2017 &copy;

update_status/templates/partial/header.html
<div class="bs-example">
    <nav class="navbar navbar-default navbar-fixed-top">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" data-target="#navbarCollapse" data-toggle="collapse" class="navbar-toggle">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="#" class="navbar-brand">Ling In</a>
        </div>
        <!-- Collection of nav links and other content for toggling -->
        <div id="navbarCollapse" class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="/update-status/">Status</a></li>
                <li><a href="/halaman-profile/">Profile</a></li>
                <li><a href="/add-friends/">Friends</a></li>
                <li><a href="/menu-stats/">Stats</a></li>
            </ul>
        </div>
    </nav>
</div>
</body>
</html>                            

update_status/templates/update_status/update_status.html
{% extends "layout/base.html" %}

{% block content %}


<section name="input-list" id="update-status-box">
    <div class="container">
        <div class="row">
            <div class="col-sm-8 col-sm-offset-2">
                <form id="form" method="POST" action="{% url 'update-status:add_todo' %}">
                    <h2><strong>Update status...</strong></h2>
                    {% csrf_token %}
                    {{ todo_form }}
                    <input id="submit" type="submit" class="btn btn-md btn-info" value="Submit">
                    <br>
                </form>
            </div>
        </div>
        
    </div>
</section>

<section name="my-list" id="show-status" style="padding-bottom: 20px; padding-top: 0px">
    {% if todo %}
        {% for data in todo %}
            <div class="container" style="padding-top: 0px">
                <div class="row">
                    <div class="col-sm-8 col-sm-offset-2">
                        <div class="media" style="padding: 40px">
                            <div class="media-left">
                                <img src="https://assets.teenvogue.com/photos/59922529fc885e5cc9aba96e/master/pass/GettyImages-546939180.jpg" class="media-object img-circle" style="width:75px"><!--foto nanti diganti dgn foto di hal profile-->
                            </div>
                            <div class="media-body">
                                <a href="/update-status/delete_status/{{ data.id }}" class="close">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </a>
                                <h4 class="media-heading"><strong>{{profile_name}}</strong> <small><i>Posted on {{data.created_date}}</i></small></h4><!--nama nanti diganti dgn nama di hal profile-->
                                <p>{{data.description}}</p>
                                

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    {% else %}
         <div class="container text-center"  style="padding-top: 15px;">
            <div class="row">
                <div class="col-sm-8 col-sm-offset-2">
                    <div id="empty" class="alert alert-danger">
                        <strong>Oops!</strong> Anda belum membuat status apapun.
                    </div>
                    
                </div>
            </div>
            
        </div>
    {% endif %}
    
</section>

{% endblock %}        